# Generated by Django 2.0.13 on 2020-03-15 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('link', models.CharField(max_length=300)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('country_name', models.CharField(blank=True, max_length=30, null=True)),
                ('city_id', models.CharField(blank=True, max_length=20, null=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=300, null=True)),
                ('picture_url', models.CharField(blank=True, max_length=500, null=True)),
                ('posting_cnt', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
