# Generated by Django 2.0.13 on 2020-03-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postings'),
    ]

    operations = [
        migrations.AddField(
            model_name='postings',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
